### ISSUE TITLE
How do you exclude methods?

### ISSUE THREAD

**Issue by cevatkerim** [supamii/ah-swagger-plugin#10]
Currently it lists everything whether the api supports it or not.

get,post, etc..

Also, how do you limit the documentation to the ones that are configured in the routes?

**Comment by supamii** [comment]
Damn, sorry for the delay...  

You'll want to create a configuration file config/swagger.js

``` javascript
  exports['default'] = { 
    swagger: function(api){
      return {
        // Generate documentation for simple actions specified by action-name
        documentSimpleRoutes: false,
        // Generate documentation for actions specified under config/routes.js
        documentConfigRoutes: true,
      }
    }
  }
```

Let me know if this makes sense

**Comment by supamii** [comment]
Closing question.
