### ISSUE TITLE
Create the first release tag 

### ISSUE THREAD

**Issue by asilvino** [supamii/ah-swagger-plugin#13]
Hello,

wouldn't be better/great to track the versions of the plugin?

I there any way to create the first release tag? (just an idea not really an issue)

**Comment by supamii** [comment]
That's true - it would definitely help organization and what not.

**Comment by supamii** [comment]
If it makes sense - and to get the ball rolling - I'll just create a tag based on the version currently posted on npm?

i don't really have any methodical system behind versioning other than to get up on npm.org  ;)

**Comment by asilvino** [comment]
That's sounds just like what I would do.
You can just add +0.1 for bug resolves and add +1.0 for big changes and new features. 
What you think?

**Comment by supamii** [comment]
sure! - makes sense!  i do enjoy actionherojs's model too where any breaking changes that require refactors is a major version increment

**Comment by evantahler** [comment]
That's not just actionhero's model, that's what SEMVER is _supposed_ to do: http://semver.org/

**Comment by supamii** [comment]
Dropping a friendly FYI:  With some of the recent re-organizations - I went ahead and cut a release at 1.0.0 -- thanks for the contributions and input!
