### ISSUE TITLE
If `api.config.servers.web.simpleRouting` is disabled, plugin breaks

### ISSUE THREAD

**Issue by evantahler** [supamii/ah-swagger-plugin#2]

**Comment by evantahler** [comment]
Also:

`api.config.swagger.documentSimpleRoutes` and `api.config.swagger.documentConfigRoutes` are is probably an extraneous config option, and you can just follow the configs in web (if they are enabled, you document them)

**Comment by supamii** [comment]
Ty @evantahler - Yep, it would be empty if it was disabled.

**Comment by supamii** [comment]
@evantahler after some thought regarding the extraneous config option, i wanted to mimic actionhero's "toDocument" option and allow the user to hide a set of APIs.  Which actually brings to mind that perhaps I could simply follow suit and use toDocument or come up with something more intuitive
