### ISSUE TITLE
How to upload a file using swagger

### ISSUE THREAD

**Issue by sanmoy27** [supamii/ah-swagger-plugin#22]
I am using ah-swagger plugin

modelSchema: {
		file: {
			type: 'file'
		}
	}

the option for choosing the file is not coming,

used the content-type as application/binary

pls help.

**Comment by supamii** [comment]
sounds like your latest commit should help resolve this?  @sanmoy27   great work btw

**Comment by sanmoy27** [comment]
yes it got resolved and I need to update the doc,how do I do that

**Comment by supamii** [comment]
npmjs.com should be updating - we can reopen if the publish doesn't kick in - checkout v1.0.1 to find your changes!
