### ISSUE TITLE
api.swagger.host assumes that configured port is public port

### ISSUE THREAD

**Issue by Onfire7** [supamii/ah-swagger-plugin#6]
api.swagger.host includes the port, and appears to not have a config option to override the port that it gets from the server configuration.

While this is fine most of the time, if your API server is behind a reverse proxy or NAT firewall that changes the port that the public uses to reach the api server, all of the examples in swagger-ui are broken, and it displays an incorrect url for the action.

If a PR is needed, I would be happy to provide one.

**Comment by evantahler** [comment]
I think it makes sense to source this information from the actionhero server _most of the time_.  Perhaps we don't need a default option, but rather an `host_ovveride` and `port_override` options?

**Comment by Onfire7** [comment]
Yeah, that's one of the things I thought was weird, it requires that you set a host, but then pulls the port from the config without providing a way to change it. I think pulling both from the server, and then allowing you to override them makes more sense.

**Comment by evantahler** [comment]
@supamii, your thoughts?

**Comment by supamii** [comment]
Hi friends, Can't believe it's been 23 days... I'll definitely get this overridden with something more sensible - i.e. host_override and port_override

**Comment by supamii** [comment]
Admittedly a bit of a configuration nightmare, but I've now set the config parameter baseUrl to omit the port number entirely.

This means one may specify
baseUrl: 'myserverip:8080'

or alternatively set
hostOverride: 'myserverip',
portOverride: 8080

I hope this helps!
