### ISSUE TITLE
add a screenshot to the readme! 

### ISSUE THREAD

**Issue by evantahler** [supamii/ah-swagger-plugin#8]
people like pretty pictures

**Comment by evantahler** [comment]
Here's one: 

<img width="997" alt="screen shot 2015-09-06 at 11 45 46 am" src="https://cloud.githubusercontent.com/assets/303226/9705999/d9b11d8a-548c-11e5-8573-60dc4347acf1.png">

**Comment by supamii** [comment]
Good idea

**Comment by supamii** [comment]
I used the default sample - admittedly out of laziness but I'm interested in throwing up a better looking one.  Will mark as closed for now.
